### ISSUE TITLE
murakami container fails to run

### ISSUE THREAD

**Issue by stephen-soltesz** [m-lab/murakami#6]
The current murakami container fails to run due to a deprecated API at freegeoip.net

Specifically, http://freegeoip.net/json now redirects to http://freegeoip.net/shutdown 

The updated API requires an API key.

Logs from murakami due to this error:
```
Traceback (most recent call last):
  File "run.py", line 100, in <module>
    perform_test_loop()
  File "run.py", line 75, in perform_test_loop
    f = urllib2.urlopen('http://freegeoip.net/json')
  File "/usr/lib/python2.7/urllib2.py", line 154, in urlopen
    return opener.open(url, data, timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 467, in error
    result = self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 654, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "/usr/lib/python2.7/urllib2.py", line 435, in open
    response = meth(req, response)
  File "/usr/lib/python2.7/urllib2.py", line 548, in http_response
    'http', request, response, code, msg, hdrs)
  File "/usr/lib/python2.7/urllib2.py", line 473, in error
    return self._call_chain(*args)
  File "/usr/lib/python2.7/urllib2.py", line 407, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 556, in http_error_default
    raise HTTPError(req.get_full_url(), code, msg, hdrs, fp)
urllib2.HTTPError: HTTP Error 403: Forbidden
```

Message from http://freegeoip.net/shutdown 
```
{
  "0": "#################################################################################################################################",
  "1": "#                                                                                                                               #",
  "2": "# IMPORTANT - PLEASE UPDATE YOUR API ENDPOINT                                                                                   #",
  "3": "#                                                                                                                               #",
  "4": "# This API endpoint is deprecated and has now been shut down. To keep using the freegeoip API, please update your integration   #",
  "5": "# to use the new ipstack API endpoint, designed as a simple drop-in replacement.                                                #",
  "6": "# You will be required to create an account at https://ipstack.com and obtain an API access key.                                #",
  "7": "#                                                                                                                               #",
  "8": "# For more information on how to upgrade please visit our Github Tutorial at: https://github.com/apilayer/freegeoip#readme      #",
  "9": "#                                                                                                                               #",
  "a": "#################################################################################################################################"
}
```

**Comment by arqtv** [comment]
Just installed Docker on Raspberry Pi and run hello-world successfully and then installed measurementlab/murakami and it would appear the container fails to run and after debugging traceback tells me I have the Issue #6 geoip error. Can I assume a sudo apt-get update will fix this? Or do I need to do more? Also whats the cli to get the version of murakami I am running? Thanks.

**Comment by arqtv** [comment]
Hi Stephen

Thank you for your prompt response. I will wait for the update on Pi as this is the hardware platform of choice. I wish to deploy this on several remote edge points in a WISP I run out in Costa Rica. We have three or four edge points where our network connects to the incumbent ISP in Costa Rica (ICE) and the Pi’s will be used to monitor each of the ISP connection “goodness”. The Pi is ideal as a low cost probe and the Murakami tool looks like it should provide us with the data we need to monitor the performance of these edge connections.

Will we need end to end IPv6 for this set up to work? Or will it work over IPv4 only? 
  
Is there a simple “Is it all working” test I can run that will tell me all is good - or not good as the case may be? I have been monitoring /var/log/daemon.log but it is a little hard to understand the output without knowing what “good” output should look like.

Many thanks

Peter

**Comment by stephen-soltesz** [comment]
@arqtv I've pushed a new image that fixes the issue originally reported here. You should be able to use it by using the docker image `measurementlab/murakami:1.1`

The NDT client should work for IPv6 or IPv4 if the local environment supports it. Docker probably needs special configuration to support native IPv6, for example.

Your question about an "is it all working" test may be best directed to support@measurementlab.net

**Comment by arqtv** [comment]
Thank you Stephen. I will try the new image and let you know.

Peter

**Comment by rr326** [comment]
@stephen-soltesz I just tried 1.1 and it worked on a fresh Raspberry pi 3 model B, with all system software updated as of 3/25/19. Confirmed.

Also, I think you should update the README.md to refer to 1.1 instead of 1.0, then maybe close this.

**Comment by stephen-soltesz** [comment]
@rr326 Done.
