### ISSUE TITLE
Add device_id to each runner's output 

### ISSUE THREAD

**Issue by robertodauria** [m-lab/murakami#61]
Each device should have a unique device ID, passed in via command-line flag (`--device-id`) or environment variables (`MURAKAMI_DEVICE_ID`).

This device ID should also be included in each test runner's output, in a field named `MurakamiDeviceID`.

**Comment by critzo** [comment]
Within each Balena managed device, in the container context the following environment variable is available: BALENA_DEVICE_UUID
This can be read by the Murakami test runners to add the deviceId field to the test output.

**Comment by robertodauria** [comment]
Closed by https://github.com/m-lab/murakami/pull/63.
