### ISSUE TITLE
convert.py fails if some test output files have different fields

### ISSUE THREAD

**Issue by robertodauria** [m-lab/murakami#68]
Test output formats change over time. `speedtest-cli` has added some new fields (e.g. `serverUrl2`) that were not there years ago.

Currently, the code reads the fields from the first record it finds, then proceeds to write the CSV header line based on that. When it finds new fields, it fails. It should either ignore new fields or include them in the header line.

**Comment by critzo** [comment]
Since the conversion of Y1 data only needs to happen once, I'll manage to get around the errors and parse the data, then close out this branch.
